### ISSUE TITLE
how to construct/destory ImpactTracker instances?

### ISSUE THREAD

**Issue by leondz** [Breakend/experiment-impact-tracker#11]
I'd like to be able to explicitly stop tracking. `experiment_impact_tracker.compute_tracker.ImpactTracker` doesn't seem to have a destructor, and doesn't implement `__enter__` & `__exit__` so can't be used with a `with`. What's the preferred route for this?

**Comment by Breakend** [comment]
The expected use case was to just start tracking at the top of the script and to stop when it exits (to limit amount of code needed to add the tool). It seems like this is a common usecase, so we will prioritize implementing this. See #5

**Comment by Breakend** [comment]
Tracking this in #5 so closing this out for now to track the effort to implement this there.
