### ISSUE TITLE
ImpactTracker Warnings 

### ISSUE THREAD

**Issue by giorgiacantisani** [Breakend/experiment-impact-tracker#34]
Hi!

I was wondering if it is normal to get the following warnings when using ImpactTracker:

![image](https://user-images.githubusercontent.com/16143204/98126818-4aa2da80-1eb6-11eb-82e3-e740c66864f6.png)

My code is:

    # Init tracker with log path and start it in a separate process
    carbon_dir = os.path.join(conf['exp_dir'], 'carbon_logs')
    os.makedirs(carbon_dir, exist_ok=True)  
    tracker = ImpactTracker(carbon_dir)
    tracker.launch_impact_monitor()

**Comment by Breakend** [comment]
This is fixed on the main branch, these are just for informing users of the timing of gathering certain metrics. It's been changed to info so it doesn't show up anymore. We'll package a new release soonish and close out this issue when it's released. If you'd like to get rid of the warnings, you can install from source for now or change this code from warn to info like in main: https://github.com/Breakend/experiment-impact-tracker/blob/a55f5d85467fe20c9543b61e1042bb19ddc6357f/experiment_impact_tracker/compute_tracker.py#L118-L120

**Comment by giorgiacantisani** [comment]
Thank you very much!

For the moment I solved in the following way: 

````
tracker = ImpactTracker(carbon_dir)

c_handler = tracker.logger.handlers[0]
c_handler.setLevel(logging.CRITICAL)

tracker.launch_impact_monitor()
