### ISSUE TITLE
Carbon statement with impact 0

### ISSUE THREAD

**Issue by pnovoa** [Breakend/experiment-impact-tracker#46]
Hello, very good project. Thanks for sharing. I have run my_experiment.py on a Linux virtual machine (Ubuntu) and then running the script generate_carbon_impact_statement with "USA" I get the following output: "This work contributed 0.000 kg of....", that is, with 0s in all indicators. Is this normal? Thanks in advance....

**Comment by jieru-hu** [comment]
hi @pnovoa! Could you provide a minimal repro so it'd be easier for us to investigate? for example 
 your logs and  the command you used to generate the statement? 

thanks!

**Comment by pnovoa** [comment]
> hi @pnovoa! Could you provide a minimal repro so it'd be easier for us to investigate? for example
> your logs and the command you used to generate the statement?
> 
> thanks!

I have run the following command:

generate-carbon-impact-statement /tmp/tmp4b0gac2l/ "USA"

while the content of the folder tmp4b0gac2l is as in the zip file below:
[tmp4b0gac2l.zip](https://github.com/Breakend/experiment-impact-tracker/files/5811574/tmp4b0gac2l.zip)

Thanks

**Comment by Breakend** [comment]
Hi, 

So, it looks like the tool isn't able to find any power readings from either a GPU or CPU. Does the Ubuntu machine have nvidia-smi installed? Also do you see anything under the directory /sys/class/powercap/intel-rapl/ ?

For the tool to track energy, it needs to have certain firmware dependencies (Intel's RAPL and/or nvidia-smi installed). We've added an issue to prevent silent failures like this one and will update this issue once that's done. In the meantime, I think you need to set up your machine to expose Intel rapl and nvidia-smi to actually get any energy readings.

**Comment by Breakend** [comment]
Hi, I assume this is resolved. If it's not, please let us know and re-open the issue. Thanks!
