### ISSUE TITLE
Feature Request: Add ability to manually stop tracking

### ISSUE THREAD

**Issue by Breakend** [Breakend/experiment-impact-tracker#5]

**Comment by Breakend** [comment]
From #11 "I'd like to be able to explicitly stop tracking. experiment_impact_tracker.compute_tracker.ImpactTracker doesn't seem to have a destructor, and doesn't implement __enter__ & __exit__ so can't be used with a with. What's the preferred route for this?".

**Comment by leondz** [comment]
Something like this works:

```
#!usr/bin/env python3.7
import time
import experiment_impact_tracker
import experiment_impact_tracker.compute_tracker
import experiment_impact_tracker.data_utils

tracker = experiment_impact_tracker.compute_tracker.ImpactTracker("x1")
tracker.launch_impact_monitor()
time.sleep(10)
tracker.p.terminate()
experiment_impact_tracker.data_utils.log_final_info(tracker.logdir)

time.sleep(20)

tracker = experiment_impact_tracker.compute_tracker.ImpactTracker("x2")
tracker.launch_impact_monitor()
time.sleep(10)
tracker.p.terminate()
experiment_impact_tracker.data_utils.log_final_info(tracker.logdir)
```

The second launch clobbers the data from the first. It would be good to able to supply a parameter to `launch_impact_monitor` to name individual runs without reinstantiating the object. 

On a related side note, it's not immediately clear why the output dir has a single`impacttracker` subdir before the output files. Perhaps multiple subdirs would make more sense, one per `launch_impact_monitor` call, named by e.g. start utime by default?

**Comment by leondz** [comment]
A destructor should also clear up file handles etc; currently doing the above repeatedly results in an OSError (too many open files)

**Comment by Breakend** [comment]
We are working on this now, I think we want to leave the tracker as separate for each experiment to ensure no accidental clobbering. We add an impacttracker folder so you can ensure that all logs will be isolated there. For example:

```python

tracker = ImpactTracker(mylogdir)
tracker.launch_impact_monitor()
with open(os.path.join(mylogdir, 'my_experiment_log.csv')) as f:
    f.write(f"{experiment_data}\n")
```

Then your logs will be in your experiment's logdir but you'll also have the experiment_impact_tracker logs right in the same folder.

**Comment by Breakend** [comment]
I am not getting an OSError for file handles on either of my systems. Please open a new issue if you're still getting this problem and we'll try to get to the bottom of it.
