### ISSUE TITLE
Getting an error in get_zone_information_by_coords

### ISSUE THREAD

**Issue by guillaumeramey** [Breakend/experiment-impact-tracker#65]
Hi, I'm trying to add the tracker in my project but I keep getting the same error when launching the tracker :

```
/usr/local/lib/python3.7/dist-packages/experiment_impact_tracker/emissions/get_region_metrics.py in get_zone_information_by_coords(coords)
      6 def get_zone_information_by_coords(coords):
      7     region = get_region_by_coords(coords)
----> 8     return region, ZONE_INFO[region["id"]]
      9 
     10 def get_region_by_coords(coords):

KeyError: 'US-NV'
```

Any idea of why ?

**Comment by Breakend** [comment]
Hi, it looks like for some reason the data store didn't have an average carbon intensity for nevada. I've added it in the master branch at c1b0fcb4e75f04511805a1e57b2d8a97266d2977 . Please pull master, try again, and let us know if the error remains. Thanks!

**Comment by guillaumeramey** [comment]
Thank you Breakend, This issue is now solved.
