### ISSUE TITLE
ModuleNotFoundError: No module named 'experiment_impact_tracker.data_interface'

### ISSUE THREAD

**Issue by mjay42** [Breakend/experiment-impact-tracker#71]
Hi all,

I am testing the library on a simple tutorial from Pytorch. I was able to generate an "impacttracker" folder and data.json seems to contain the expected information. However, I am not able to use the DataInterface class: 

```
>>> from experiment_impact_tracker.data_interface import DataInterface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'experiment_impact_tracker.data_interface'
```

I use Anaconda environments. I have tried downgrading python to versions 3.7 and 3.8.
I have noticed my version of experiment_impact_tracker is 0.1.8 even though the version.py file specifies 0.1.9 but running "pip install experiment-impact-tracker --upgrade" doesn't fix it.

Here is my system info:
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-9-amd64
Architecture: x86-64 

Thank you in advance for your help.

**Comment by Breakend** [comment]
Hi, we haven't released a new version just yet with the data interface. Please install from the main branch:

pip install git+https://github.com/Breakend/experiment-impact-tracker.git

**Comment by mjay42** [comment]
Hi Peter,

Thank you for your help!

Best,
Mathilde
